default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: <%= ENV['POSTGRES_POOL'] %>
  database: <%= ENV['POSTGRES_DATABASE'] %>
local: &local
  <<: *default
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *local
  database: desafio_tech_development
test:
  <<: *local
  database: desafio_tech_test
production:
  <<: *default